title: Sodiq Jinad
name:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

<img src="/img/headshot.jpg" alt="OT Boy" width="45%" />

<img src="/img/headshot.jpg" alt="Boy OT" width="25%" /> <embed>
description: This is a site for personal portfolio and other nice stuffs
